# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import CommonService_pb2 as CommonService__pb2
from . import ExperimentRunService_pb2 as ExperimentRunService__pb2


class ExperimentRunServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.createExperimentRun = channel.unary_unary(
        '/com.mitdbg.modeldb.ExperimentRunService/createExperimentRun',
        request_serializer=ExperimentRunService__pb2.CreateExperimentRun.SerializeToString,
        response_deserializer=ExperimentRunService__pb2.CreateExperimentRun.Response.FromString,
        )
    self.deleteExperimentRun = channel.unary_unary(
        '/com.mitdbg.modeldb.ExperimentRunService/deleteExperimentRun',
        request_serializer=ExperimentRunService__pb2.DeleteExperimentRun.SerializeToString,
        response_deserializer=ExperimentRunService__pb2.DeleteExperimentRun.Response.FromString,
        )
    self.getExperimentRunsInProject = channel.unary_unary(
        '/com.mitdbg.modeldb.ExperimentRunService/getExperimentRunsInProject',
        request_serializer=ExperimentRunService__pb2.GetExperimentRunsInProject.SerializeToString,
        response_deserializer=ExperimentRunService__pb2.GetExperimentRunsInProject.Response.FromString,
        )
    self.getExperimentRun = channel.unary_unary(
        '/com.mitdbg.modeldb.ExperimentRunService/getExperimentRun',
        request_serializer=ExperimentRunService__pb2.GetExperimentRun.SerializeToString,
        response_deserializer=ExperimentRunService__pb2.GetExperimentRun.Response.FromString,
        )
    self.updateExperimentRunNameOrDescription = channel.unary_unary(
        '/com.mitdbg.modeldb.ExperimentRunService/updateExperimentRunNameOrDescription',
        request_serializer=ExperimentRunService__pb2.UpdateExperimentRunNameOrDescription.SerializeToString,
        response_deserializer=ExperimentRunService__pb2.UpdateExperimentRunNameOrDescription.Response.FromString,
        )
    self.addExperimentRunTags = channel.unary_unary(
        '/com.mitdbg.modeldb.ExperimentRunService/addExperimentRunTags',
        request_serializer=ExperimentRunService__pb2.AddExperimentRunTags.SerializeToString,
        response_deserializer=ExperimentRunService__pb2.AddExperimentRunTags.Response.FromString,
        )
    self.deleteExperimentRunTags = channel.unary_unary(
        '/com.mitdbg.modeldb.ExperimentRunService/deleteExperimentRunTags',
        request_serializer=ExperimentRunService__pb2.DeleteExperimentRunTags.SerializeToString,
        response_deserializer=ExperimentRunService__pb2.DeleteExperimentRunTags.Response.FromString,
        )
    self.logObservation = channel.unary_unary(
        '/com.mitdbg.modeldb.ExperimentRunService/logObservation',
        request_serializer=ExperimentRunService__pb2.LogObservation.SerializeToString,
        response_deserializer=ExperimentRunService__pb2.LogObservation.Response.FromString,
        )
    self.getObservations = channel.unary_unary(
        '/com.mitdbg.modeldb.ExperimentRunService/getObservations',
        request_serializer=ExperimentRunService__pb2.GetObservations.SerializeToString,
        response_deserializer=ExperimentRunService__pb2.GetObservations.Response.FromString,
        )
    self.logMetric = channel.unary_unary(
        '/com.mitdbg.modeldb.ExperimentRunService/logMetric',
        request_serializer=ExperimentRunService__pb2.LogMetric.SerializeToString,
        response_deserializer=ExperimentRunService__pb2.LogMetric.Response.FromString,
        )
    self.getMetrics = channel.unary_unary(
        '/com.mitdbg.modeldb.ExperimentRunService/getMetrics',
        request_serializer=ExperimentRunService__pb2.GetMetrics.SerializeToString,
        response_deserializer=ExperimentRunService__pb2.GetMetrics.Response.FromString,
        )
    self.logDataset = channel.unary_unary(
        '/com.mitdbg.modeldb.ExperimentRunService/logDataset',
        request_serializer=ExperimentRunService__pb2.LogDataset.SerializeToString,
        response_deserializer=ExperimentRunService__pb2.LogDataset.Response.FromString,
        )
    self.getDatasets = channel.unary_unary(
        '/com.mitdbg.modeldb.ExperimentRunService/getDatasets',
        request_serializer=ExperimentRunService__pb2.GetDatasets.SerializeToString,
        response_deserializer=ExperimentRunService__pb2.GetDatasets.Response.FromString,
        )
    self.logArtifact = channel.unary_unary(
        '/com.mitdbg.modeldb.ExperimentRunService/logArtifact',
        request_serializer=ExperimentRunService__pb2.LogArtifact.SerializeToString,
        response_deserializer=ExperimentRunService__pb2.LogArtifact.Response.FromString,
        )
    self.getArtifacts = channel.unary_unary(
        '/com.mitdbg.modeldb.ExperimentRunService/getArtifacts',
        request_serializer=ExperimentRunService__pb2.GetArtifacts.SerializeToString,
        response_deserializer=ExperimentRunService__pb2.GetArtifacts.Response.FromString,
        )
    self.logHyperparameter = channel.unary_unary(
        '/com.mitdbg.modeldb.ExperimentRunService/logHyperparameter',
        request_serializer=ExperimentRunService__pb2.LogHyperparameter.SerializeToString,
        response_deserializer=ExperimentRunService__pb2.LogHyperparameter.Response.FromString,
        )
    self.getHyperparameters = channel.unary_unary(
        '/com.mitdbg.modeldb.ExperimentRunService/getHyperparameters',
        request_serializer=ExperimentRunService__pb2.GetHyperparameters.SerializeToString,
        response_deserializer=ExperimentRunService__pb2.GetHyperparameters.Response.FromString,
        )
    self.logAttribute = channel.unary_unary(
        '/com.mitdbg.modeldb.ExperimentRunService/logAttribute',
        request_serializer=ExperimentRunService__pb2.LogAttribute.SerializeToString,
        response_deserializer=ExperimentRunService__pb2.LogAttribute.Response.FromString,
        )
    self.getAttributes = channel.unary_unary(
        '/com.mitdbg.modeldb.ExperimentRunService/getAttributes',
        request_serializer=CommonService__pb2.GetAttributes.SerializeToString,
        response_deserializer=CommonService__pb2.GetAttributes.Response.FromString,
        )
    self.storeArtifact = channel.unary_unary(
        '/com.mitdbg.modeldb.ExperimentRunService/storeArtifact',
        request_serializer=ExperimentRunService__pb2.ExperimentRunStoreArtifact.StoreArtifact.SerializeToString,
        response_deserializer=ExperimentRunService__pb2.ExperimentRunStoreArtifact.StoreArtifact.Response.FromString,
        )
    self.storeArtifactWithStream = channel.unary_unary(
        '/com.mitdbg.modeldb.ExperimentRunService/storeArtifactWithStream',
        request_serializer=ExperimentRunService__pb2.ExperimentRunStoreArtifact.StoreArtifactWithStream.SerializeToString,
        response_deserializer=ExperimentRunService__pb2.ExperimentRunStoreArtifact.StoreArtifactWithStream.Response.FromString,
        )
    self.getStoreArtifact = channel.unary_unary(
        '/com.mitdbg.modeldb.ExperimentRunService/getStoreArtifact',
        request_serializer=ExperimentRunService__pb2.ExperimentRunStoreArtifact.GetArtifact.SerializeToString,
        response_deserializer=ExperimentRunService__pb2.ExperimentRunStoreArtifact.GetArtifact.Response.FromString,
        )
    self.deleteStoreArtifact = channel.unary_unary(
        '/com.mitdbg.modeldb.ExperimentRunService/deleteStoreArtifact',
        request_serializer=ExperimentRunService__pb2.ExperimentRunStoreArtifact.DeleteArtifact.SerializeToString,
        response_deserializer=ExperimentRunService__pb2.ExperimentRunStoreArtifact.DeleteArtifact.Response.FromString,
        )


class ExperimentRunServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def createExperimentRun(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def deleteExperimentRun(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getExperimentRunsInProject(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getExperimentRun(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def updateExperimentRunNameOrDescription(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def addExperimentRunTags(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def deleteExperimentRunTags(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def logObservation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getObservations(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def logMetric(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getMetrics(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def logDataset(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getDatasets(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def logArtifact(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getArtifacts(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def logHyperparameter(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getHyperparameters(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def logAttribute(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getAttributes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def storeArtifact(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def storeArtifactWithStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getStoreArtifact(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def deleteStoreArtifact(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ExperimentRunServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'createExperimentRun': grpc.unary_unary_rpc_method_handler(
          servicer.createExperimentRun,
          request_deserializer=ExperimentRunService__pb2.CreateExperimentRun.FromString,
          response_serializer=ExperimentRunService__pb2.CreateExperimentRun.Response.SerializeToString,
      ),
      'deleteExperimentRun': grpc.unary_unary_rpc_method_handler(
          servicer.deleteExperimentRun,
          request_deserializer=ExperimentRunService__pb2.DeleteExperimentRun.FromString,
          response_serializer=ExperimentRunService__pb2.DeleteExperimentRun.Response.SerializeToString,
      ),
      'getExperimentRunsInProject': grpc.unary_unary_rpc_method_handler(
          servicer.getExperimentRunsInProject,
          request_deserializer=ExperimentRunService__pb2.GetExperimentRunsInProject.FromString,
          response_serializer=ExperimentRunService__pb2.GetExperimentRunsInProject.Response.SerializeToString,
      ),
      'getExperimentRun': grpc.unary_unary_rpc_method_handler(
          servicer.getExperimentRun,
          request_deserializer=ExperimentRunService__pb2.GetExperimentRun.FromString,
          response_serializer=ExperimentRunService__pb2.GetExperimentRun.Response.SerializeToString,
      ),
      'updateExperimentRunNameOrDescription': grpc.unary_unary_rpc_method_handler(
          servicer.updateExperimentRunNameOrDescription,
          request_deserializer=ExperimentRunService__pb2.UpdateExperimentRunNameOrDescription.FromString,
          response_serializer=ExperimentRunService__pb2.UpdateExperimentRunNameOrDescription.Response.SerializeToString,
      ),
      'addExperimentRunTags': grpc.unary_unary_rpc_method_handler(
          servicer.addExperimentRunTags,
          request_deserializer=ExperimentRunService__pb2.AddExperimentRunTags.FromString,
          response_serializer=ExperimentRunService__pb2.AddExperimentRunTags.Response.SerializeToString,
      ),
      'deleteExperimentRunTags': grpc.unary_unary_rpc_method_handler(
          servicer.deleteExperimentRunTags,
          request_deserializer=ExperimentRunService__pb2.DeleteExperimentRunTags.FromString,
          response_serializer=ExperimentRunService__pb2.DeleteExperimentRunTags.Response.SerializeToString,
      ),
      'logObservation': grpc.unary_unary_rpc_method_handler(
          servicer.logObservation,
          request_deserializer=ExperimentRunService__pb2.LogObservation.FromString,
          response_serializer=ExperimentRunService__pb2.LogObservation.Response.SerializeToString,
      ),
      'getObservations': grpc.unary_unary_rpc_method_handler(
          servicer.getObservations,
          request_deserializer=ExperimentRunService__pb2.GetObservations.FromString,
          response_serializer=ExperimentRunService__pb2.GetObservations.Response.SerializeToString,
      ),
      'logMetric': grpc.unary_unary_rpc_method_handler(
          servicer.logMetric,
          request_deserializer=ExperimentRunService__pb2.LogMetric.FromString,
          response_serializer=ExperimentRunService__pb2.LogMetric.Response.SerializeToString,
      ),
      'getMetrics': grpc.unary_unary_rpc_method_handler(
          servicer.getMetrics,
          request_deserializer=ExperimentRunService__pb2.GetMetrics.FromString,
          response_serializer=ExperimentRunService__pb2.GetMetrics.Response.SerializeToString,
      ),
      'logDataset': grpc.unary_unary_rpc_method_handler(
          servicer.logDataset,
          request_deserializer=ExperimentRunService__pb2.LogDataset.FromString,
          response_serializer=ExperimentRunService__pb2.LogDataset.Response.SerializeToString,
      ),
      'getDatasets': grpc.unary_unary_rpc_method_handler(
          servicer.getDatasets,
          request_deserializer=ExperimentRunService__pb2.GetDatasets.FromString,
          response_serializer=ExperimentRunService__pb2.GetDatasets.Response.SerializeToString,
      ),
      'logArtifact': grpc.unary_unary_rpc_method_handler(
          servicer.logArtifact,
          request_deserializer=ExperimentRunService__pb2.LogArtifact.FromString,
          response_serializer=ExperimentRunService__pb2.LogArtifact.Response.SerializeToString,
      ),
      'getArtifacts': grpc.unary_unary_rpc_method_handler(
          servicer.getArtifacts,
          request_deserializer=ExperimentRunService__pb2.GetArtifacts.FromString,
          response_serializer=ExperimentRunService__pb2.GetArtifacts.Response.SerializeToString,
      ),
      'logHyperparameter': grpc.unary_unary_rpc_method_handler(
          servicer.logHyperparameter,
          request_deserializer=ExperimentRunService__pb2.LogHyperparameter.FromString,
          response_serializer=ExperimentRunService__pb2.LogHyperparameter.Response.SerializeToString,
      ),
      'getHyperparameters': grpc.unary_unary_rpc_method_handler(
          servicer.getHyperparameters,
          request_deserializer=ExperimentRunService__pb2.GetHyperparameters.FromString,
          response_serializer=ExperimentRunService__pb2.GetHyperparameters.Response.SerializeToString,
      ),
      'logAttribute': grpc.unary_unary_rpc_method_handler(
          servicer.logAttribute,
          request_deserializer=ExperimentRunService__pb2.LogAttribute.FromString,
          response_serializer=ExperimentRunService__pb2.LogAttribute.Response.SerializeToString,
      ),
      'getAttributes': grpc.unary_unary_rpc_method_handler(
          servicer.getAttributes,
          request_deserializer=CommonService__pb2.GetAttributes.FromString,
          response_serializer=CommonService__pb2.GetAttributes.Response.SerializeToString,
      ),
      'storeArtifact': grpc.unary_unary_rpc_method_handler(
          servicer.storeArtifact,
          request_deserializer=ExperimentRunService__pb2.ExperimentRunStoreArtifact.StoreArtifact.FromString,
          response_serializer=ExperimentRunService__pb2.ExperimentRunStoreArtifact.StoreArtifact.Response.SerializeToString,
      ),
      'storeArtifactWithStream': grpc.unary_unary_rpc_method_handler(
          servicer.storeArtifactWithStream,
          request_deserializer=ExperimentRunService__pb2.ExperimentRunStoreArtifact.StoreArtifactWithStream.FromString,
          response_serializer=ExperimentRunService__pb2.ExperimentRunStoreArtifact.StoreArtifactWithStream.Response.SerializeToString,
      ),
      'getStoreArtifact': grpc.unary_unary_rpc_method_handler(
          servicer.getStoreArtifact,
          request_deserializer=ExperimentRunService__pb2.ExperimentRunStoreArtifact.GetArtifact.FromString,
          response_serializer=ExperimentRunService__pb2.ExperimentRunStoreArtifact.GetArtifact.Response.SerializeToString,
      ),
      'deleteStoreArtifact': grpc.unary_unary_rpc_method_handler(
          servicer.deleteStoreArtifact,
          request_deserializer=ExperimentRunService__pb2.ExperimentRunStoreArtifact.DeleteArtifact.FromString,
          response_serializer=ExperimentRunService__pb2.ExperimentRunStoreArtifact.DeleteArtifact.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.mitdbg.modeldb.ExperimentRunService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
