# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import ProjectService_pb2 as ProjectService__pb2


class ProjectServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.createProject = channel.unary_unary(
        '/com.mitdbg.modeldb.ProjectService/createProject',
        request_serializer=ProjectService__pb2.CreateProject.SerializeToString,
        response_deserializer=ProjectService__pb2.CreateProject.Response.FromString,
        )
    self.getProjectById = channel.unary_unary(
        '/com.mitdbg.modeldb.ProjectService/getProjectById',
        request_serializer=ProjectService__pb2.GetProject.SerializeToString,
        response_deserializer=ProjectService__pb2.GetProject.Response.FromString,
        )
    self.getProjectByName = channel.unary_unary(
        '/com.mitdbg.modeldb.ProjectService/getProjectByName',
        request_serializer=ProjectService__pb2.GetProject.SerializeToString,
        response_deserializer=ProjectService__pb2.GetProject.Response.FromString,
        )
    self.getProjects = channel.unary_unary(
        '/com.mitdbg.modeldb.ProjectService/getProjects',
        request_serializer=ProjectService__pb2.GetProjects.SerializeToString,
        response_deserializer=ProjectService__pb2.GetProjects.Response.FromString,
        )
    self.deleteProject = channel.unary_unary(
        '/com.mitdbg.modeldb.ProjectService/deleteProject',
        request_serializer=ProjectService__pb2.DeleteProject.SerializeToString,
        response_deserializer=ProjectService__pb2.DeleteProject.Response.FromString,
        )
    self.updateProjectNameOrDescription = channel.unary_unary(
        '/com.mitdbg.modeldb.ProjectService/updateProjectNameOrDescription',
        request_serializer=ProjectService__pb2.UpdateProjectNameOrDescription.SerializeToString,
        response_deserializer=ProjectService__pb2.UpdateProjectNameOrDescription.Response.FromString,
        )
    self.addProjectTags = channel.unary_unary(
        '/com.mitdbg.modeldb.ProjectService/addProjectTags',
        request_serializer=ProjectService__pb2.AddProjectTags.SerializeToString,
        response_deserializer=ProjectService__pb2.AddProjectTags.Response.FromString,
        )
    self.deleteProjectTags = channel.unary_unary(
        '/com.mitdbg.modeldb.ProjectService/deleteProjectTags',
        request_serializer=ProjectService__pb2.DeleteProjectTags.SerializeToString,
        response_deserializer=ProjectService__pb2.DeleteProjectTags.Response.FromString,
        )
    self.updateProjectAttributes = channel.unary_unary(
        '/com.mitdbg.modeldb.ProjectService/updateProjectAttributes',
        request_serializer=ProjectService__pb2.UpdateProjectAttributes.SerializeToString,
        response_deserializer=ProjectService__pb2.UpdateProjectAttributes.Response.FromString,
        )
    self.getProjectAttributes = channel.unary_unary(
        '/com.mitdbg.modeldb.ProjectService/getProjectAttributes',
        request_serializer=ProjectService__pb2.GetProjectAttributes.SerializeToString,
        response_deserializer=ProjectService__pb2.GetProjectAttributes.Response.FromString,
        )


class ProjectServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def createProject(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getProjectById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getProjectByName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getProjects(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def deleteProject(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def updateProjectNameOrDescription(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def addProjectTags(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def deleteProjectTags(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def updateProjectAttributes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getProjectAttributes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProjectServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'createProject': grpc.unary_unary_rpc_method_handler(
          servicer.createProject,
          request_deserializer=ProjectService__pb2.CreateProject.FromString,
          response_serializer=ProjectService__pb2.CreateProject.Response.SerializeToString,
      ),
      'getProjectById': grpc.unary_unary_rpc_method_handler(
          servicer.getProjectById,
          request_deserializer=ProjectService__pb2.GetProject.FromString,
          response_serializer=ProjectService__pb2.GetProject.Response.SerializeToString,
      ),
      'getProjectByName': grpc.unary_unary_rpc_method_handler(
          servicer.getProjectByName,
          request_deserializer=ProjectService__pb2.GetProject.FromString,
          response_serializer=ProjectService__pb2.GetProject.Response.SerializeToString,
      ),
      'getProjects': grpc.unary_unary_rpc_method_handler(
          servicer.getProjects,
          request_deserializer=ProjectService__pb2.GetProjects.FromString,
          response_serializer=ProjectService__pb2.GetProjects.Response.SerializeToString,
      ),
      'deleteProject': grpc.unary_unary_rpc_method_handler(
          servicer.deleteProject,
          request_deserializer=ProjectService__pb2.DeleteProject.FromString,
          response_serializer=ProjectService__pb2.DeleteProject.Response.SerializeToString,
      ),
      'updateProjectNameOrDescription': grpc.unary_unary_rpc_method_handler(
          servicer.updateProjectNameOrDescription,
          request_deserializer=ProjectService__pb2.UpdateProjectNameOrDescription.FromString,
          response_serializer=ProjectService__pb2.UpdateProjectNameOrDescription.Response.SerializeToString,
      ),
      'addProjectTags': grpc.unary_unary_rpc_method_handler(
          servicer.addProjectTags,
          request_deserializer=ProjectService__pb2.AddProjectTags.FromString,
          response_serializer=ProjectService__pb2.AddProjectTags.Response.SerializeToString,
      ),
      'deleteProjectTags': grpc.unary_unary_rpc_method_handler(
          servicer.deleteProjectTags,
          request_deserializer=ProjectService__pb2.DeleteProjectTags.FromString,
          response_serializer=ProjectService__pb2.DeleteProjectTags.Response.SerializeToString,
      ),
      'updateProjectAttributes': grpc.unary_unary_rpc_method_handler(
          servicer.updateProjectAttributes,
          request_deserializer=ProjectService__pb2.UpdateProjectAttributes.FromString,
          response_serializer=ProjectService__pb2.UpdateProjectAttributes.Response.SerializeToString,
      ),
      'getProjectAttributes': grpc.unary_unary_rpc_method_handler(
          servicer.getProjectAttributes,
          request_deserializer=ProjectService__pb2.GetProjectAttributes.FromString,
          response_serializer=ProjectService__pb2.GetProjectAttributes.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.mitdbg.modeldb.ProjectService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
