# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ArtifactStore_pb2 as ArtifactStore__pb2


class ArtifactStoreStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.storeArtifact = channel.unary_unary(
        '/com.mitdbg.artifactstore.ArtifactStore/storeArtifact',
        request_serializer=ArtifactStore__pb2.StoreArtifact.SerializeToString,
        response_deserializer=ArtifactStore__pb2.StoreArtifact.Response.FromString,
        )
    self.storeArtifactWithStream = channel.unary_unary(
        '/com.mitdbg.artifactstore.ArtifactStore/storeArtifactWithStream',
        request_serializer=ArtifactStore__pb2.StoreArtifactWithStream.SerializeToString,
        response_deserializer=ArtifactStore__pb2.StoreArtifactWithStream.Response.FromString,
        )
    self.getArtifact = channel.unary_unary(
        '/com.mitdbg.artifactstore.ArtifactStore/getArtifact',
        request_serializer=ArtifactStore__pb2.GetArtifact.SerializeToString,
        response_deserializer=ArtifactStore__pb2.GetArtifact.Response.FromString,
        )
    self.deleteArtifact = channel.unary_unary(
        '/com.mitdbg.artifactstore.ArtifactStore/deleteArtifact',
        request_serializer=ArtifactStore__pb2.DeleteArtifact.SerializeToString,
        response_deserializer=ArtifactStore__pb2.DeleteArtifact.Response.FromString,
        )


class ArtifactStoreServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def storeArtifact(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def storeArtifactWithStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getArtifact(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def deleteArtifact(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ArtifactStoreServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'storeArtifact': grpc.unary_unary_rpc_method_handler(
          servicer.storeArtifact,
          request_deserializer=ArtifactStore__pb2.StoreArtifact.FromString,
          response_serializer=ArtifactStore__pb2.StoreArtifact.Response.SerializeToString,
      ),
      'storeArtifactWithStream': grpc.unary_unary_rpc_method_handler(
          servicer.storeArtifactWithStream,
          request_deserializer=ArtifactStore__pb2.StoreArtifactWithStream.FromString,
          response_serializer=ArtifactStore__pb2.StoreArtifactWithStream.Response.SerializeToString,
      ),
      'getArtifact': grpc.unary_unary_rpc_method_handler(
          servicer.getArtifact,
          request_deserializer=ArtifactStore__pb2.GetArtifact.FromString,
          response_serializer=ArtifactStore__pb2.GetArtifact.Response.SerializeToString,
      ),
      'deleteArtifact': grpc.unary_unary_rpc_method_handler(
          servicer.deleteArtifact,
          request_deserializer=ArtifactStore__pb2.DeleteArtifact.FromString,
          response_serializer=ArtifactStore__pb2.DeleteArtifact.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.mitdbg.artifactstore.ArtifactStore', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
